# this is redis config file
[list]
    [list.default]
        proxy_list = ["129.204.120.143:6379"]
        conn_timeout = 500
        password = "875466528"
        db = 0
        read_timeout = 1000
        write_timeout = 1000
        max_active = 200
        max_idle = 500